teams:
  - name: acapy-admins
    maintainers:
      - swcurran
    members:
      - WadeBarnes
      - TimoGlastra
      - andrewwhitehead
      - dbluhm
  - name: acapy-committers
    maintainers:
      - swcurran
    members:
      - TelegramSam
      - andrewwhitehead
      - TimoGlastra
      - WadeBarnes
      - amanji
      - chumbert
      - dbluhm
      - esune
      - ianco
      - jamshale
      - ff137
      - thiagoromanos
      - PatStLouis
  - name: acapy-contributors
    maintainers:
      - swcurran
    members:
      - TelegramSam
      - WadeBarnes
      - Jsyro
      - dbluhm
      - esune
      - ianco
      - jamshale
      - TheTechmage
  - name: askar-admins
    maintainers:
      - andrewwhitehead
    members:
      - TimoGlastra
      - WadeBarnes
      - swcurran
  - name: askar-maintainers
    maintainers:
      - andrewwhitehead
    members:
      - berendsliedrecht
      - genaris
  - name: askar-wrapper-javascript-admins
    maintainers:
      - TimoGlastra
    members:
      - andrewwhitehead
      - swcurran
  - name: askar-wrapper-javascript-maintainers
    maintainers:
      - TimoGlastra
    members:
      - cvarjao
      - berendsliedrecht
      - genaris
  - name: architecture-sig-maintainers
    maintainers:
      - tkuhrt
  - name: bifold-wallet-maintainers
    maintainers:
      - jleach
    members:
      - amanji
      - bryce-mcmath
      - cvarjao
      - wadeking98
      - jcdrouin21
      - MosCD3
      - thiagoromanos
  - name: bots
    maintainers:
      - ryjones
    members:
      - owf-bot
  - name: credential-comparison-format-sig-committers
    maintainers:
      - cre8
      - tkuhrt
      - tlodderstedt
  - name: credential-comparison-format-sig-admins
    maintainers:
      - cre8
  - name: credo-admins
    maintainers:
      - TimoGlastra
  - name: credo-maintainers
    maintainers:
      - jakubkoci
      - TimoGlastra
    members:
      - berendsliedrecht
      - genaris
      - auer-martin
  - name: didcomm-admins
    maintainers:
      - dbluhm
    members:
      - WadeBarnes
      - TimoGlastra
      - andrewwhitehead
      - swcurran
  - name: didcomm-committers
    maintainers:
      - swcurran
    members:
      - TelegramSam
      - andrewwhitehead
      - TimoGlastra
      - WadeBarnes
      - dbluhm
      - esune
      - ianco
      - jamshale
      - TheTechmage
  - name: didcomm-contributors
    maintainers:
      - swcurran
    members:
      - TelegramSam
      - WadeBarnes
      - dbluhm
      - esune
      - ianco
      - jamshale
  - name: digital-wallet-and-agent-overviews-sig-maintainers
    maintainers:
      - cre8
    members:
      - samuelmr
  - name: digital-wallet-and-agent-overviews-sig-admins
    maintainers:
      - cre8
  - name: lf-employees
    maintainers:
      - ryjones
      - strawberry-baked-alaska
      - tbenzies
    members:
      - SeanBohan
      - mkdolan
  - name: owl-agent-test-harness-admins
    maintainers:
      - nodlesh
      - swcurran
  - name: owl-agent-test-harness-committers
    maintainers:
      - swcurran
      - PatStLouis
    members:
      - AmarjeetAkv
      - jamshale
      - gmulhearn
      - genaris
      - Patrik-Stas
      - WadeBarnes
      - geethutnair94
      - usingtechnology
      - mirgee
      - Jsyro
      - lauravuo
      - tdiesler
      - ianco
      - Moopli
      - nodlesh
  - name: owl-akrida-admins
    maintainers:
      - KimEbert42
    members:
      - swcurran
      - nodlesh
  - name: owl-akrida-committers
    maintainers:
      - KimEbert42
    members:
      - nodlesh
      - AmarjeetAkv
      - anwalker293
      - loneil
      - rajpalc7
      - GHkrishna
      - dbluhm
  - name: owl-mobile-wallet-test-harness-admins
    maintainers:
      - nodlesh
  - name: owl-mobile-wallet-test-harness-committers
    maintainers:
      - nodlesh
    members:
      - AmarjeetAkv
  - name: safe-wallet-sig-maintainers
    maintainers:
      - tkuhrt
    members:
      - skounis
      - darrellodonnell
  - name: sd-jwt-js-admin
    maintainers:
    - cre8
    members:
    - lukasjhan
  - name: sd-jwt-js-maintainers
    maintainers:
    - cre8
    members:
    - aceshim
    - berendsliedrecht
    - lukasjhan
    - zustkeeper
  - name: tac
    maintainers:
      - tkuhrt
    members:
      - davidz25
      - rolsonquadras
      - petecool
      - aceshim
      - skounis
      - swcurran
      - wenjing
repositories:
  - name: .github
    teams:
      tac: maintain
    visibility: public
  - name: acapy
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
    visibility: public
  - name: acapy-plugins
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
    visibility: public
  - name: acapy-controllers
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
    visibility: public
  - name: acapy-tools
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
    visibility: public
  - name: acapy-endorser-service
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
    visibility: public
  - name: askar
    teams:
      askar-admins: admin
      askar-maintainers: maintain
  - name: askar-wrapper-javascript
    teams:
      askar-wrapper-javascript-admins: admin
      askar-admins: admin
      askar-wrapper-javascript-maintainers: maintain
      askar-maintainers: maintain
  - name: architecture-sig
    teams:
      architecture-sig-maintainers: maintain
    visibility: public
  - name: bifold-wallet
    teams:
      bifold-wallet-maintainers: maintain
    visibility: public
  - name: credential-format-comparison-sig
    teams:
      credential-comparison-format-sig-admins: admin
      credential-comparison-format-sig-committers: maintain
    visibility: public
  - name: credo-ts
    teams:
      credo-admins: admin
      credo-maintainers: maintain
    visibility: public
  - name: credo-ts-docs
    teams:
      credo-admins: admin
      credo-maintainers: maintain
    visibility: public
  - name: credo-ts-ext
    teams:
      credo-admins: admin
      credo-maintainers: maintain
    visibility: public
  - name: didcomm-mediator-service
    teams:
      didcomm-admins: admin
      didcomm-committers: maintain
      didcomm-contributors: read
    visibility: public
  - name: digital-wallet-and-agent-overviews-sig
    teams:
      digital-wallet-and-agent-overviews-sig-admins: admin
      digital-wallet-and-agent-overviews-sig-maintainers: maintain
    visibility: public
  - name: openwallet-foundation-landscape
    visibility: private
  - name: owl
    teams:
      owl-mobile-wallet-test-harness-admins: admin
      owl-mobile-wallet-test-harness-committers: triage
      owl-agent-test-harness-admins: admin
      owl-agent-test-harness-committers: triage
      owl-akrida-admins: admin
      owl-akrida-committers: triage
    visibility: public
  - name: owl-mobile-wallet-test-harness
    teams:
      bifold-wallet-maintainers: maintain
      owl-mobile-wallet-test-harness-admins: admin
      owl-mobile-wallet-test-harness-committers: maintain
    visibility: public
  - name: project-proposals
    teams:
      tac: maintain
    visibility: public
  - name: safe-wallet-sig
    teams:
      safe-wallet-sig-maintainers: maintain
    visibility: public
  - name: sd-jwt-js
    teams:
      sd-jwt-js-maintainers: maintain
      sd-jwt-js-admin: admin
    visibility: public
  - name: tac
    teams:
      tac: maintain
    visibility: public
  - name: owl-agent-test-harness
    teams:
      acapy-committers: maintain
      credo-maintainers: maintain
      bots: maintain
      owl-agent-test-harness-admins: admin
      owl-agent-test-harness-committers: maintain
    visibility: public
  - name: owl-akrida
    teams:
      acapy-committers: maintain
      credo-maintainers: maintain
      owl-akrida-admins: admin
      owl-akrida-committers: maintain
    visibility: public
